id: 17d3926dbd384dacbae251285d4d9f48
initial_creation_type: ocr
source_metadata:
  volumes:
    1185b60dab384550afdbc75b497437f6:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: ''
      total_pages: 1044
      volume_number: 38
